# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details and example of testing OPTIONAL modules

language: php

dist: trusty

php:
  - 5.5

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=4

matrix:
  include:
    - php: 5.6
      env:
        - DB=MYSQL
        - PHPCS_TEST=1
    - php: 7.0
      env:
        - DB=PGSQL
    - php: 7.1
      env:
        - DB=MYSQL
        - PDO=1

before_script:
  - composer self-update || true
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs listingpage/src/ listingpage/tests/ -n; fi
  - vendor/bin/phpunit listingpage/tests/
